version: '3.8'
services:
  api:
    image: kz159/walld_api:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=172.17.0.1

  rmq:
    image: "rabbitmq:management-alpine"
    ports:
      - "15672:15672"
      - "5672:5672"

  pexels:
    image: kz159/walld_grab_pexels:latest
    environment: &env
      - RMQ_HOST=rmq
      - INTERVAL=180
      - PER_PAGE=20
      - DB_HOST=172.17.0.1

  tg_bot:
    image: kz159/walld_tg_bot:latest
    environment:
    - RMQ_HOST=rmq
    - DB_HOST=172.17.0.1
    - TG_TOKEN= YOUR_TG_TOKEN_HERE

  aku_aku: 
    image: kz159/walld_aku_aku:latest
    environment:
    - RMQ_HOST=rmq
    - DB_HOST=172.17.0.1
    - PIC_URL= YOUR_DOMAIN
    depends_on:
      - rmq
    volumes:
      - ./pics:/app/pics

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./pics:/usr/share/nginx/html"
